/*
 * Knowledge Graph Service
 * The Knowledge Graph Service lets you find entities and categories in the knowledge graph. This service is particularly suited to be run as a second step after the Entity Linking Service has been used for linking ambiguous names in natural-language texts to entities. With this service, you can now explore these entities further. 
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ambiverse.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.api.client.util.Key;

/**
 * Licence
 */
public class Licence   {

  @Key
  @JsonProperty("name")
  private String name;

  @Key
  @JsonProperty("url")
  private String url = null;

  public Licence withName(String name) {
    this.name = name;
    return this;
  }
  /**
   * The licence name
   * @return name
   **/
  @JsonProperty("name")
  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }



  public Licence withUrl(String url) {
    this.url = url;
    return this;
  }

  /**
   * The licence url
   * @return url
   **/
  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

